"""Add intraday tracking and update alert rules

Revision ID: 5bededbee6b1
Revises: 01a54e7435ff
Create Date: 2025-12-27 09:32:00.572291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bededbee6b1'
down_revision: Union[str, None] = '01a54e7435ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intraday_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('market_phase', sa.String(length=20), nullable=False),
    sa.Column('is_gap_down_checked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intraday_price_snapshots_id'), 'intraday_price_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_intraday_price_snapshots_snapshot_time'), 'intraday_price_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_intraday_price_snapshots_stock_symbol'), 'intraday_price_snapshots', ['stock_symbol'], unique=False)
    op.create_index('ix_symbol_phase_time', 'intraday_price_snapshots', ['stock_symbol', 'market_phase', 'snapshot_time'], unique=False)
    op.create_index('ix_symbol_snapshot_time', 'intraday_price_snapshots', ['stock_symbol', 'snapshot_time'], unique=False)
    op.add_column('alert_rules', sa.Column('check_interval_seconds', sa.Integer(), nullable=False, server_default='900'))
    op.create_index(op.f('ix_alert_rules_alert_type'), 'alert_rules', ['alert_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_rules_alert_type'), table_name='alert_rules')
    op.drop_column('alert_rules', 'check_interval_seconds')
    op.drop_index('ix_symbol_snapshot_time', table_name='intraday_price_snapshots')
    op.drop_index('ix_symbol_phase_time', table_name='intraday_price_snapshots')
    op.drop_index(op.f('ix_intraday_price_snapshots_stock_symbol'), table_name='intraday_price_snapshots')
    op.drop_index(op.f('ix_intraday_price_snapshots_snapshot_time'), table_name='intraday_price_snapshots')
    op.drop_index(op.f('ix_intraday_price_snapshots_id'), table_name='intraday_price_snapshots')
    op.drop_table('intraday_price_snapshots')
    # ### end Alembic commands ###
